# Generated by Django 4.1.1 on 2022-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="platforms",
            field=models.ManyToManyField(
                blank=True, related_name="product", to="gaming_shop.platform"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
