# Generated by Django 4.1.1 on 2022-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming_shop", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
