# Generated by Django 4.1.1 on 2023-01-04 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_userbase_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbase",
            name="date_of_birth",
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
