# Generated by Django 4.1.1 on 2023-01-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_userbase_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbase",
            name="username",
        ),
    ]
